services:
    dojobot:
        image: dojobot
        build: .
        env_file:
            - .env
        logging:
            options:
                max-size: 1m
                max-file: 2
                compress: "true"
        restart: on-failure
        stop_grace_period: 1s
        tty: true
        deploy:
            resources:
                limits:
                    memory: 80M
